export enum KiokuElement {
    Flame = "Flame",
    Aqua = "Aqua",
    Forest = "Forest",
    Light = "Light",
    Dark = "Dark",
    Void = "Void"
}

export enum Aliment {
    BURN = "BURN",
    CURSE = "CURSE",
    POISON = "POISON",
    STUN = "STUN",
    VORTEX = "VORTEX",
    WEAKNESS = "WEAKNESS",
    WOUND = "BLEED",
}

export const elementAlimentMap: Record<KiokuElement, Aliment> = {
    [KiokuElement.Flame]: Aliment.BURN,
    [KiokuElement.Aqua]: Aliment.WEAKNESS,
    [KiokuElement.Forest]: Aliment.POISON,
    [KiokuElement.Light]: Aliment.STUN,
    [KiokuElement.Dark]: Aliment.CURSE,
    [KiokuElement.Void]: Aliment.WOUND,
};

export enum KiokuRole {
    Attacker = "Attacker",
    Buffer = "Buffer",
    Debuffer = "Debuffer",
    Healer = "Healer",
    Breaker = "Breaker",
    Defender = "Defender"
}

export const roleMap: Record<string, KiokuRole> = {
    1: KiokuRole.Attacker,
    2: KiokuRole.Breaker,
    3: KiokuRole.Healer,
    4: KiokuRole.Buffer,
    5: KiokuRole.Debuffer,
    6: KiokuRole.Defender,
};

export type SupportKey = KiokuRole | KiokuElement

export const elementMap: Record<string, KiokuElement> = {
    1: KiokuElement.Flame,
    2: KiokuElement.Aqua,
    3: KiokuElement.Forest,
    4: KiokuElement.Light,
    5: KiokuElement.Dark,
    6: KiokuElement.Void,
};

export const LuxMagica = "Lux☆Magica"

export const maxPlayerLevel = 160

export const scoreAttackRelevantBuffsAndDebuffs = {
    DWN_DEF_ACCUM_RATIO: "Accumulated DEFf%-",
    DWN_DEF_RATIO: "DEF%-",
    DWN_ELEMENT_RESIST_ACCUM_RATIO: "Accumulated Elemental Resistance-",
    DWN_ELEMENT_RESIST_RATIO: "Elemental Resistance-",
    FLAT_ATK: "Flat ATK",
    UP_AIM_RCV_DMG_RATIO: "Element Specific DMG Taken%+",
    UP_ATK_ACCUM_RATIO: "Accumulated ATK%+",
    UP_ATK_FIXED: "ATK+",
    UP_ATK_RATIO: "ATK%+",
    UP_ATK_CONSUME_RATIO: "One Turn ATK%+",
    UP_CTD_ACCUM_RATIO: "Accumulated Crit Damage%+",
    UP_CTD_FIXED: "Crit Damage+",
    UP_CTD_RATIO: "Crit Damage%+",
    UP_CTR_ACCUM_RATIO: "Accumulated Crit Rate+",
    UP_CTR_FIXED: "Crit Rate+",
    UP_CTR_RATIO: "Crit Rate+",
    UP_DEF_ACCUM_RATIO: "Accumulated DEF%+",
    UP_DEF_FIXED: "Flat DEF",
    UP_DEF_RATIO: "DEF%+",
    ADDITIONAL_DAMAGE: "Additional DMG",
    UP_ELEMENT_DMG_RATE_RATIO: "Elemental DMG+",
    UP_GIV_DMG_RATIO: "DMG%+",
    UP_GIV_DMG_ACCUM_RATIO: "Accumulated DMG+",
    UP_GIV_SLIP_DMG_RATIO: "DOT DMG+",
    UP_RCV_CTR_RATIO: "Hit Crit Rate%+",
    UP_RCV_DMG_RATIO: "DMG Taken%+",
    UP_WEAK_ELEMENT_DMG_RATIO: "Weak DMG+",
    WEAKNESS: "Weakness Count",
};

export const otherBuffsAndDebuffs = {
    ADD_BUFF_TURN_IMM: "ADD_BUFF_TURN_IMM",
    ADD_BUFF_TURN: "ADD_BUFF_TURN",
    ADD_DEBUFF_TURN_IMM: "ADD_DEBUFF_TURN_IMM",
    ADD_DEBUFF_TURN: "ADD_DEBUFF_TURN",
    ADDITIONAL_SKILL_ACT: "ADDITIONAL_SKILL_ACT",
    ADDITIONAL_TURN_UNIT_ACT: "ADDITIONAL_TURN_UNIT_ACT",
    BARRIER: "BARRIER",
    BLEED_ATK: "BLEED_ATK",
    BLEED_DEF: "BLEED_DEF",
    BLEED_HP: "BLEED_HP",
    BURN_ATK: "BURN_ATK",
    BURN_DEF: "BURN_DEF",
    BURN_HP: "BURN_HP",
    CHARGE: "CHARGE",
    CONSUME_CHARGE_POINT: "CONSUME_CHARGE_POINT",
    CONSUME_COUNT_POINT: "CONSUME_COUNT_POINT",
    CONSUME_ZONE_STACK: "CONSUME_ZONE_STACK",
    CONTINUOUS_RECOVERY: "CONTINUOUS_RECOVERY",
    COUNT: "COUNT",
    CURSE_ATK: "CURSE_ATK",
    CURSE_DEF: "CURSE_DEF",
    CURSE_HP: "CURSE_HP",
    CUTOUT: "CUTOUT",
    DMG_ATK: "DMG_ATK",
    DMG_DEF: "DMG_DEF",
    DMG_RANDOM: "DMG_RANDOM",
    DOWN_SPD_RATIO: "DOWN_SPD_RATIO",
    DWN_ATK_RATIO: "DWN_ATK_RATIO",
    DWN_RCV_DMG_RATIO: "Decrease DMG Taken",
    DWN_SPD_ACCUM_RATIO: "DWN_SPD_ACCUM_RATIO",
    DWN_SPD_RATIO: "DWN_SPD_RATIO",
    GAIN_CHARGE_POINT: "GAIN_CHARGE_POINT",
    GAIN_COUNT_POINT: "GAIN_COUNT_POINT",
    GAIN_EP_FIXED: "GAIN_EP_FIXED",
    GAIN_EP_RATIO: "GAIN_EP_RATIO",
    GAIN_SP_FIXED: "GAIN_SP_FIXED",
    GAIN_ZONE_STACK: "GAIN_ZONE_STACK",
    HASTE: "HASTE",
    IMM_SLIP_DMG: "IMM_SLIP_DMG",
    POISON_ATK: "POISON_ATK",
    POISON_DEF: "POISON_DEF",
    POISON_HP: "POISON_HP",
    RE_ACTION_TURN_UNIT_ACT: "RE_ACTION_TURN_UNIT_ACT",
    RECOVERY_HP_ATK: "RECOVERY_HP_ATK",
    RECOVERY_HP: "RECOVERY_HP",
    REFLECTION_RATIO: "REFLECTION_RATIO",
    REGAIN_ATK: "REGAIN_ATK",
    REMOVE_ALL_ABNORMAL: "REMOVE_ALL_ABNORMAL",
    REMOVE_ALL_BUFF: "REMOVE_ALL_BUFF",
    REMOVE_ALL_DEBUFF: "REMOVE_ALL_DEBUFF",
    RESET_UNIQUE_BUFF: "RESET_UNIQUE_BUFF",
    RESET_UNIQUE_DEBUFF: "RESET_UNIQUE_DEBUFF",
    SHIELD: "SHIELD",
    SLOW: "SLOW",
    STUN: "STUN",
    SWITCH_SKILL: "SWITCH_SKILL",
    TSUBAME_CORE: "TSUBAME_CORE",
    TSUBAME_LINK: "TSUBAME_LINK",
    TSUBAME: "TSUBAME",
    UNIQUE_10030301: "UNIQUE_10030301",
    UNIQUE_10070201: "UNIQUE_10070201",
    UNIQUE_BUFF_ACCUM: "UNIQUE_BUFF_ACCUM",
    UNIQUE_BUFF: "UNIQUE_BUFF",
    UNIQUE_DEBUFF_ACCUM: "UNIQUE_DEBUFF_ACCUM",
    UNIQUE_DEBUFF: "UNIQUE_DEBUFF",
    UNIQUE_ZONE: "UNIQUE_ZONE",
    UP_ABNORMAL_HIT_RATE_RATIO: "Ailment Hit Rate",
    UP_ABNORMAL_PARRY_RATE_RATIO: "Ailment Dodge Rate",
    UP_BREAK_DAMAGE_RECEIVE_RATIO: "UP_BREAK_DAMAGE_RECEIVE_RATIO",
    UP_BREAK_EFFECT: "Break Effect",
    UP_BUFF_EFFECT_VALUE: "UP_BUFF_EFFECT_VALUE",
    UP_DEBUFF_EFFECT_VALUE: "UP_DEBUFF_EFFECT_VALUE",
    DWN_BUFF_EFFECT_VALUE: "DWN_BUFF_EFFECT_VALUE",
    DWN_DEBUFF_EFFECT_VALUE: "DWN_DEBUFF_EFFECT_VALUE",
    UP_EFFECT_HIT_RATE_RATIO: "Debuff Hit Rate",
    UP_EFFECT_PARRY_RATE_RATIO: "Debuff Dodge Rate",
    UP_EP_RECOVER_RATE_RATIO: "MP%+",
    UP_GIV_BREAK_POINT_DMG_FIXED: "UP_GIV_BREAK_POINT_DMG_FIXED",
    UP_GIV_VORTEX_DMG_RATIO: "UP_GIV_VORTEX_DMG_RATIO",
    UP_HATE: "UP_HATE",
    UP_HEAL_RATE_RATIO: "Heal% Rate",
    UP_HP_FIXED: "HP+",
    UP_HP_RATIO: "HP%+",
    UP_RCV_BREAK_POINT_DMG_RATIO: "UP_RCV_BREAK_POINT_DMG_RATIO",
    UP_SPD_ACCUM_RATIO: "UP_SPD_ACCUM_RATIO",
    UP_SPD_FIXED: "Spd Increase",
    UP_SPD_RATIO: "Spd% Increase",
    VORTEX_ATK: "VORTEX_ATK",
    ZONE_EXPAND: "ZONE_EXPAND",
    ZONE_STACK: "ZONE_STACK",
    UP_ELEMENT_DMG_RATE_RATIO_FLAME: "Elemental DMG+ (Flame)",
    UP_ELEMENT_DMG_RATE_RATIO_AQUA: "Elemental DMG+ (Aqua)",
    UP_ELEMENT_DMG_RATE_RATIO_FOREST: "Elemental DMG+ (Forest)",
    UP_ELEMENT_DMG_RATE_RATIO_LIGHT: "Elemental DMG+ (Light)",
    UP_ELEMENT_DMG_RATE_RATIO_DARK: "Elemental DMG+ (Dark)",
    UP_ELEMENT_DMG_RATE_RATIO_VOID: "Elemental DMG+ (Void)",
};
