// GENERATED from GameAssembly 3.19.0 (UnitStateBase.CanAddTo overrides), see MISSING_AND_UNCERTAIN R6.
// A skill detail's element/role only filters targets for these STATE effect types:
//   RoleAndElement: DamageBetter/ParameterVariation/... CanAddTo (0x15b8090) -> unit role AND element must match
//   RoleOnly:       Up/DownElementDamageRate CanAddTo (0x15b9e40) -> only role; element is the boosted damage element
// Every other effect type (all DMG_*, element resist, aim, ...) never filters: for DMG_* the
// element is the ATTACK element (DamageAbilityEffectBase.attackElement), for the others it is a parameter.
export const STATE_ADD_FILTER: Record<string, "RoleAndElement" | "RoleOnly"> = {
    CPN_UP_GIV_BREAK_POINT_DMG_RATIO: "RoleAndElement",
    CPN_UP_GIV_DMG_RATIO: "RoleAndElement",
    DWN_ATK_ACCUM_RATIO: "RoleAndElement",
    DWN_ATK_CONSUME_RATIO: "RoleAndElement",
    DWN_ATK_RATIO: "RoleAndElement",
    DWN_BARRIER_VALUE: "RoleAndElement",
    DWN_BREAKED_DAMAGE_RECEIVE_RATIO: "RoleAndElement",
    DWN_BREAK_DAMAGE_RECEIVE_RATIO: "RoleAndElement",
    DWN_CTD_ACCUM_RATIO: "RoleAndElement",
    DWN_CTD_CONSUME_FIXED: "RoleAndElement",
    DWN_CTD_FIXED: "RoleAndElement",
    DWN_CTD_RATIO: "RoleAndElement",
    DWN_CTR_ACCUM_RATIO: "RoleAndElement",
    DWN_CTR_CONSUME_FIXED: "RoleAndElement",
    DWN_CTR_FIXED: "RoleAndElement",
    DWN_CTR_RATIO: "RoleAndElement",
    DWN_DEF_ACCUM_RATIO: "RoleAndElement",
    DWN_DEF_RATIO: "RoleAndElement",
    DWN_ELEMENT_DMG_RATE_RATIO: "RoleOnly",
    DWN_EP_RECOVER_RATE_RATIO: "RoleAndElement",
    DWN_GIV_BLEED_DMG_RATIO: "RoleAndElement",
    DWN_GIV_BREAK_POINT_DMG_FIXED: "RoleAndElement",
    DWN_GIV_BURN_DMG_RATIO: "RoleAndElement",
    DWN_GIV_CURSE_DMG_RATIO: "RoleAndElement",
    DWN_GIV_DMG_ACCUM_RATIO: "RoleAndElement",
    DWN_GIV_DMG_CONSUME_RATIO: "RoleAndElement",
    DWN_GIV_DMG_RATIO: "RoleAndElement",
    DWN_GIV_POISON_DMG_RATIO: "RoleAndElement",
    DWN_GIV_SLIP_DMG_RATIO: "RoleAndElement",
    DWN_GIV_VORTEX_DMG_RATIO: "RoleAndElement",
    DWN_HEAL_RATE_RATIO: "RoleAndElement",
    DWN_RCV_BREAK_POINT_DMG_RATIO: "RoleAndElement",
    DWN_RCV_DMG_RATIO: "RoleAndElement",
    DWN_RCV_RECOVERY_RATIO: "RoleAndElement",
    DWN_RECOVERY_EP_RATE_RATIO: "RoleAndElement",
    DWN_SPD_ACCUM_RATIO: "RoleAndElement",
    DWN_SPD_FIXED: "RoleAndElement",
    DWN_SPD_RATIO: "RoleAndElement",
    GVE_UP_FINAL_GAIN_EP_RATIO: "RoleAndElement",
    GVE_UP_SPECIAL_ATTACK_FINAL_GIV_DMG_RATIO: "RoleAndElement",
    REGAIN_ATK: "RoleAndElement",
    REGAIN_DEF: "RoleAndElement",
    REGAIN_HP: "RoleAndElement",
    UP_ABNORMAL_HIT_RATE_RATIO: "RoleAndElement",
    UP_ABNORMAL_PARRY_RATE_RATIO: "RoleAndElement",
    UP_ATK_ACCUM_RATIO: "RoleAndElement",
    UP_ATK_CONSUME_FIXED: "RoleAndElement",
    UP_ATK_CONSUME_RATIO: "RoleAndElement",
    UP_ATK_FIXED: "RoleAndElement",
    UP_ATK_RATIO: "RoleAndElement",
    UP_BREAKED_DAMAGE_RECEIVE_RATIO: "RoleAndElement",
    UP_BREAK_DAMAGE_RECEIVE_RATIO: "RoleAndElement",
    UP_BREAK_EFFECT: "RoleAndElement",
    UP_CTD_ACCUM_RATIO: "RoleAndElement",
    UP_CTD_CONSUME_FIXED: "RoleAndElement",
    UP_CTD_FIXED: "RoleAndElement",
    UP_CTD_RATIO: "RoleAndElement",
    UP_CTR_ACCUM_RATIO: "RoleAndElement",
    UP_CTR_CONSUME_FIXED: "RoleAndElement",
    UP_CTR_FIXED: "RoleAndElement",
    UP_CTR_RATIO: "RoleAndElement",
    UP_DEF_ACCUM_RATIO: "RoleAndElement",
    UP_DEF_FIXED: "RoleAndElement",
    UP_DEF_RATIO: "RoleAndElement",
    UP_EFFECT_HIT_RATE_RATIO: "RoleAndElement",
    UP_EFFECT_PARRY_RATE_RATIO: "RoleAndElement",
    UP_ELEMENT_DMG_RATE_RATIO: "RoleOnly",
    UP_EP_RECOVER_RATE_RATIO: "RoleAndElement",
    UP_GIV_BLEED_DMG_RATIO: "RoleAndElement",
    UP_GIV_BREAK_POINT_DMG_FIXED: "RoleAndElement",
    UP_GIV_BREAK_POINT_DMG_RATIO: "RoleAndElement",
    UP_GIV_BURN_DMG_RATIO: "RoleAndElement",
    UP_GIV_CURSE_DMG_RATIO: "RoleAndElement",
    UP_GIV_DMG_ACCUM_RATIO: "RoleAndElement",
    UP_GIV_DMG_CONSUME_RATIO: "RoleAndElement",
    UP_GIV_DMG_RATIO: "RoleAndElement",
    UP_GIV_POISON_DMG_RATIO: "RoleAndElement",
    UP_GIV_SLIP_DMG_RATIO: "RoleAndElement",
    UP_GIV_VORTEX_DMG_RATIO: "RoleAndElement",
    UP_HEAL_RATE_RATIO: "RoleAndElement",
    UP_HP_FIXED: "RoleAndElement",
    UP_HP_RATIO: "RoleAndElement",
    UP_RCV_BREAK_POINT_DMG_RATIO: "RoleAndElement",
    UP_RCV_DMG_RATIO: "RoleAndElement",
    UP_RECOVERY_EP_RATE_RATIO: "RoleAndElement",
    UP_SPD_ACCUM_RATIO: "RoleAndElement",
    UP_SPD_FIXED: "RoleAndElement",
    UP_SPD_RATIO: "RoleAndElement",
    UP_WEAK_ELEMENT_DMG_ACCUM_RATIO: "RoleAndElement",
    UP_WEAK_ELEMENT_DMG_CONSUME_RATIO: "RoleAndElement",
    UP_WEAK_ELEMENT_DMG_RATIO: "RoleAndElement",
}

// Every effect type created through UnitStateFactory (i.e. applied as a UnitState). For these the
// trigger only checks the START conditions; the ACTIVE conditions gate the state afterwards
// (UnitStateBase.IsActive), so e.g. Final Fatebloom's "while Abyssal Rose" passives must be added
// at battle start even though Abyssal Rose isn't on her yet.
export const UNIT_STATE_TYPES = new Set<string>([
    "ADDITIONAL_DAMAGE",
    "ADD_BUFF_TURN",
    "ADD_DEBUFF_TURN",
    "BARRIER",
    "BLEED_ATK",
    "BLEED_DEF",
    "BLEED_HP",
    "BURN_ATK",
    "BURN_DEF",
    "BURN_HP",
    "COMBO",
    "CONTINUOUS_RECOVERY",
    "COUNT",
    "COUNTDOWN_START",
    "CPN_UP_GIV_BREAK_POINT_DMG_RATIO",
    "CPN_UP_GIV_DMG_RATIO",
    "CURSE_ATK",
    "CURSE_DEF",
    "CURSE_HP",
    "CUTOUT",
    "DWN_AIM_GIV_DMG_RATIO",
    "DWN_AIM_RCV_DMG_RATIO",
    "DWN_ATK_ACCUM_RATIO",
    "DWN_ATK_CONSUME_RATIO",
    "DWN_ATK_RATIO",
    "DWN_BARRIER_VALUE",
    "DWN_BREAKED_DAMAGE_RECEIVE_RATIO",
    "DWN_BREAK_DAMAGE_RECEIVE_RATIO",
    "DWN_BUFF_EFFECT_VALUE",
    "DWN_CTD_ACCUM_RATIO",
    "DWN_CTD_CONSUME_FIXED",
    "DWN_CTD_FIXED",
    "DWN_CTD_RATIO",
    "DWN_CTR_ACCUM_RATIO",
    "DWN_CTR_CONSUME_FIXED",
    "DWN_CTR_FIXED",
    "DWN_CTR_RATIO",
    "DWN_DEBUFF_EFFECT_VALUE",
    "DWN_DEF_ACCUM_RATIO",
    "DWN_DEF_RATIO",
    "DWN_ELEMENT_DMG_RATE_RATIO",
    "DWN_ELEMENT_RESIST_ACCUM_RATIO",
    "DWN_EP_RECOVER_RATE_RATIO",
    "DWN_GIV_BLEED_DMG_RATIO",
    "DWN_GIV_BREAK_POINT_DMG_FIXED",
    "DWN_GIV_BURN_DMG_RATIO",
    "DWN_GIV_CURSE_DMG_RATIO",
    "DWN_GIV_DMG_ACCUM_RATIO",
    "DWN_GIV_DMG_CONSUME_RATIO",
    "DWN_GIV_DMG_RATIO",
    "DWN_GIV_POISON_DMG_RATIO",
    "DWN_GIV_SLIP_DMG_RATIO",
    "DWN_GIV_VORTEX_DMG_RATIO",
    "DWN_HATE",
    "DWN_HEAL_RATE_RATIO",
    "DWN_RCV_BREAK_POINT_DMG_RATIO",
    "DWN_RCV_DMG_RATIO",
    "DWN_RCV_RECOVERY_RATIO",
    "DWN_RECOVERY_EP_RATE_RATIO",
    "DWN_SPD_ACCUM_RATIO",
    "DWN_SPD_FIXED",
    "DWN_SPD_RATIO",
    "GVE_UP_FINAL_GAIN_EP_RATIO",
    "GVE_UP_SPECIAL_ATTACK_FINAL_GIV_DMG_RATIO",
    "LOCK_SPECIAL_ATTACK",
    "LOCK_TURN_ORDER",
    "POISON_ATK",
    "POISON_DEF",
    "POISON_HP",
    "PREVENT_ABNORMAL",
    "RCV_FINAL_DAMAGE",
    "REFLECTION_RATIO",
    "REGAIN_ATK",
    "REGAIN_DEF",
    "REGAIN_HP",
    "SHIELD",
    "STUN",
    "SWITCH_SKILL",
    "TSUBAME_CORE",
    "TSUBAME_LINK",
    "UNIQUE_10030301",
    "UNIQUE_10070201",
    "UNIQUE_BUFF",
    "UNIQUE_BUFF_ACCUM",
    "UNIQUE_DEBUFF",
    "UNIQUE_DEBUFF_ACCUM",
    "UNIQUE_ELEMENT_BREAK",
    "UNIQUE_ELEMENT_STACK",
    "UNIQUE_ENEMY_639002",
    "UNIQUE_ZONE",
    "UP_ABNORMAL_HIT_RATE_RATIO",
    "UP_ABNORMAL_PARRY_RATE_RATIO",
    "UP_AIM_GIV_DMG_RATIO",
    "UP_AIM_RCV_DMG_RATIO",
    "UP_ATK_ACCUM_RATIO",
    "UP_ATK_CONSUME_FIXED",
    "UP_ATK_CONSUME_RATIO",
    "UP_ATK_FIXED",
    "UP_ATK_RATIO",
    "UP_BREAKED_DAMAGE_RECEIVE_RATIO",
    "UP_BREAK_DAMAGE_RECEIVE_RATIO",
    "UP_BREAK_EFFECT",
    "UP_BUFF_EFFECT_VALUE",
    "UP_CTD_ACCUM_RATIO",
    "UP_CTD_CONSUME_FIXED",
    "UP_CTD_FIXED",
    "UP_CTD_RATIO",
    "UP_CTR_ACCUM_RATIO",
    "UP_CTR_CONSUME_FIXED",
    "UP_CTR_FIXED",
    "UP_CTR_RATIO",
    "UP_DEBUFF_EFFECT_VALUE",
    "UP_DEF_ACCUM_RATIO",
    "UP_DEF_FIXED",
    "UP_DEF_RATIO",
    "UP_EFFECT_HIT_RATE_RATIO",
    "UP_EFFECT_PARRY_RATE_RATIO",
    "UP_ELEMENT_DMG_RATE_RATIO",
    "UP_ELEMENT_RESIST_ACCUM_RATIO",
    "UP_ELEMENT_RESIST_RATIO",
    "UP_EP_RECOVER_RATE_RATIO",
    "UP_GIV_BLEED_DMG_RATIO",
    "UP_GIV_BREAK_POINT_DMG_FIXED",
    "UP_GIV_BREAK_POINT_DMG_RATIO",
    "UP_GIV_BURN_DMG_RATIO",
    "UP_GIV_CURSE_DMG_RATIO",
    "UP_GIV_DMG_ACCUM_RATIO",
    "UP_GIV_DMG_CONSUME_RATIO",
    "UP_GIV_DMG_RATIO",
    "UP_GIV_POISON_DMG_RATIO",
    "UP_GIV_SLIP_DMG_RATIO",
    "UP_GIV_VORTEX_DMG_RATIO",
    "UP_HATE",
    "UP_HEAL_RATE_RATIO",
    "UP_HP_FIXED",
    "UP_HP_RATIO",
    "UP_RCV_BREAK_POINT_DMG_RATIO",
    "UP_RCV_CTD_RATIO",
    "UP_RCV_CTR_RATIO",
    "UP_RCV_DMG_RATIO",
    "UP_RECOVERY_EP_RATE_RATIO",
    "UP_SPD_ACCUM_RATIO",
    "UP_SPD_FIXED",
    "UP_SPD_RATIO",
    "UP_WEAK_ELEMENT_DMG_ACCUM_RATIO",
    "UP_WEAK_ELEMENT_DMG_CONSUME_RATIO",
    "UP_WEAK_ELEMENT_DMG_RATIO",
    "VORTEX_ATK",
    "WEAKNESS",
])
