# Run this from inside scripts/backfill-power/ before the first run, and
# again any time PowerValue.ts / AccountSimilarityScore.ts / KiokuTypes.ts /
# helpers.ts / mathFuncs.ts (or the base_data JSON files they read) change
# in your real source and you want the backfill to reflect the new version.
#
# What this does:
#   1. Copies those 5 .ts files from src/ into ./vendor/ unchanged.
#   2. Copies the base_data/*.json files helpers.ts needs into
#      ./vendor/base_data/ too, so every import stays a plain relative
#      path -- no absolute paths, no cross-drive weirdness on Windows.
#   3. Rewrites the cross-file imports in the 5 .ts files (originally
#      "../types/KiokuTypes", "../assets/base_data/...", etc.) to flat
#      "./X" imports, since everything now lives together in one folder.
#   4. Redirects the betaSettings import to a local stub with plain
#      default values (no Pinia, no per-user overrides — see
#      vendor/betaSettingsStub.ts, which is NOT generated by this script
#      and is never overwritten by it).
#   5. Strips KiokuTypes.ts's import of PvPTeam/KiokuState and the
#      BattleState interface that uses them — that's a models/PvPTeam.ts
#      dependency unrelated to scoring, not vendored here, and unused by
#      the scoring functions this script actually calls.
#
# Edit $SrcRoot below if your source folder isn't at ..\..\src relative
# to this script's location.
#
# Usage (from scripts/backfill-power/):
#   .\prepare.ps1

$SrcRoot = "..\..\src"
$VendorDir = ".\vendor"
$VendorDataDir = "$VendorDir\base_data"

if (-not (Test-Path $SrcRoot)) {
    Write-Error "Could not find $SrcRoot -- edit `$SrcRoot at the top of this script to match your repo layout."
    exit 1
}

New-Item -ItemType Directory -Force -Path $VendorDir | Out-Null
New-Item -ItemType Directory -Force -Path $VendorDataDir | Out-Null

# --- Copy the 5 code files ---
$filesToCopy = @{
    "PowerValue.ts"             = "$SrcRoot\models\PowerValue.ts"
    "AccountSimilarityScore.ts" = "$SrcRoot\models\AccountSimilarityScore.ts"
    "KiokuTypes.ts"             = "$SrcRoot\types\KiokuTypes.ts"
    "helpers.ts"                = "$SrcRoot\utils\helpers.ts"
    "mathFuncs.ts"              = "$SrcRoot\utils\mathFuncs.ts"
}

foreach ($name in $filesToCopy.Keys) {
    $source = $filesToCopy[$name]
    $dest = "$VendorDir\$name"

    if (-not (Test-Path $source)) {
        Write-Error "Could not find $source -- edit `$SrcRoot at the top of this script to match your repo layout."
        exit 1
    }

    Copy-Item -Path $source -Destination $dest -Force
    Write-Host "Copied $source -> $dest"
}

# --- Copy the JSON assets helpers.ts needs ---
$jsonFiles = @(
    "getSelectionAbilityMstList.json",
    "getCardMstList.json",
    "getCardLimitBreakMstList.json",
    "getPassiveSkillDetailMstList.json",
    "getSkillDetailMstList.json",
    "getStyleParamUpMstList.json",
    "getStyleParamUpEffectMstList.json",
    "getCharacterHeartParamUpGroupMstList.json",
    "getCharacterHeartMstList.json",
    "kioku_data.json"
)

foreach ($jsonName in $jsonFiles) {
    $source = "$SrcRoot\assets\base_data\$jsonName"
    $dest = "$VendorDataDir\$jsonName"

    if (-not (Test-Path $source)) {
        Write-Error "Could not find $source -- edit `$SrcRoot at the top of this script to match your repo layout."
        exit 1
    }

    Copy-Item -Path $source -Destination $dest -Force
}
Write-Host "Copied $($jsonFiles.Count) JSON asset files -> $VendorDataDir"

# --- Patch imports ---

# PowerValue.ts
$f = "$VendorDir\PowerValue.ts"
$content = Get-Content -Raw -Path $f
$content = $content -replace 'from\s+"\.\./types/KiokuTypes"', 'from "./KiokuTypes"'
$content = $content -replace 'from\s+"\.\./utils/betaSettings"', 'from "./betaSettingsStub"'
$content = $content -replace 'from\s+"\.\./utils/mathFuncs"', 'from "./mathFuncs"'
Set-Content -Path $f -Value $content -NoNewline
Write-Host "Patched imports in $f"

# AccountSimilarityScore.ts
$f = "$VendorDir\AccountSimilarityScore.ts"
$content = Get-Content -Raw -Path $f
$content = $content -replace 'from\s+"\.\./types/KiokuTypes"', 'from "./KiokuTypes"'
Set-Content -Path $f -Value $content -NoNewline
Write-Host "Patched imports in $f"

# KiokuTypes.ts: strip PvPTeam dependency + BattleState (unused by scoring),
# flatten its helpers.ts import.
$f = "$VendorDir\KiokuTypes.ts"
$content = Get-Content -Raw -Path $f
$content = $content -replace 'import\s*\{\s*PvPTeam,\s*KiokuState\s*\}\s*from\s*"\.\./models/PvPTeam";\s*\r?\n', ''
$content = $content -replace 'from\s+"\.\./utils/helpers"', 'from "./helpers"'
$content = $content -replace '(?s)export interface BattleState \{.*', ''
Set-Content -Path $f -Value $content -NoNewline
Write-Host "Patched imports in $f (removed PvPTeam dependency + BattleState, unused by scoring)"

# helpers.ts: flatten JSON asset imports to ./base_data/..., flatten its
# KiokuTypes import.
$f = "$VendorDir\helpers.ts"
$content = Get-Content -Raw -Path $f
$content = $content -replace '\.\./assets/base_data/', './base_data/'
$content = $content -replace "from\s+'\.\./types/KiokuTypes'", "from './KiokuTypes'"
Set-Content -Path $f -Value $content -NoNewline
Write-Host "Patched imports in $f"

# mathFuncs.ts has no imports, nothing to patch.

Write-Host ""
Write-Host "Done. ./vendor now has patched, self-contained copies (code + JSON data)."
Write-Host "Re-run this script any time the real source files or base_data JSON change."
